### ISSUE TITLE
application in no_std

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [mbuesch/adxl345_driver2#1]
Hi,

I gave it a shot using this driver in a `no_std` setup. I run into issues as the std library is used e.g. for result variants. 

```
104 |             return Err(AdxlError::Spi());
    |                      ^^^ not found in this scope
    |
help: consider importing this tuple variant
    |
26  + use core::result::Result::Err;

```

I started refactoring to import from `core` where possible as the help suggests. However, I'm wondering if there is a more straigt forward way that does not require changing the imports in all modules.

Cheers

**Comment by mbuesch** [comment]
In what environment do you try to build the driver?
The build with the `feature` `no_std` works fine for me on a PC.

**Comment by HerrMuellerluedenscheid** [comment]
I'm building for the rp2040. To reproduce the issue a simple way is to take [this project template](https://github.com/rp-rs/rp2040-project-template) and add the driver as a dependency:
```
❯ git diff

Δ Cargo.toml
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

────────────────────────────────────────────────────────────────────┐
• 15: panic-probe = { version = "0.3", features = ["print-defmt"] } │
────────────────────────────────────────────────────────────────────┘

# We're using a Pico by default on this template
rp-pico = "0.8"
adxl345_driver2 = { version = "2", features = ["no_std"] }

# but you can use any BSP. Uncomment this to use the pro_micro_rp2040 BSP instead
# sparkfun-pro-micro-rp2040 = "0.7"

```
Running `cargo build` yields
```
[...]
help: consider importing this tuple variant
    |
26  + use core::result::Result::Ok;
    |

Some errors have detailed explanations: E0405, E0412, E0425, E0463, E0531.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `adxl345_driver2` (lib) due to 101 previous errors
```

**Comment by mbuesch** [comment]
Ok. Interesting.
I don't know what's going on. I only use this driver with std.

**Comment by HerrMuellerluedenscheid** [comment]
Ok, thanks. I will try to fix the `no_std` for this use case.

**Comment by mbuesch** [comment]
Is the core prelude not automatically being imported here? I don't really get what's going on.
According to the documentation it should import it:
https://doc.rust-lang.org/core/prelude/index.html

**Comment by HerrMuellerluedenscheid** [comment]
Hmm that is odd in deed. I will dig a bit deeper.

**Comment by mbuesch** [comment]
I have also tried on avr bare metal. There I get the same error message.
Maybe an explicit import of the prelude is required on bare metal platforms.
Sorry, I have never really tried this before. I thought that specifying the no_std config attribute was enough for a proper build test.
